version: '3.7'
services:
  frontend:
    container_name: 'frontend-image'
    build:
     context: .
     dockerfile: Dockerfile
    ports:
      - 61300:3000
    env_file:
      - .env
    restart: always